server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mdblog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Bql879543~
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      # 更新或者创建数据表结构
      ddl-auto: update

    # 控制台显示SQL
    show-sql: true
    database: mysql